language: php

php:
  - 5.3
  - 5.4

env:
  - SYMFONY_VERSION=v2.0.5
  - SYMFONY_VERSION=origin/master

before_script: php vendor/vendors.php

notifications:
  irc: irc.freenode.net#vespolina
  recipients: cordoval@gmail.com
  email:
    on_success: always